- hosts: dockerd11
  tasks:

     - name: run cowrie
       shell: |
         #sudo su - cowrie
         cd cowrie
         source cowrie-env/bin/activate
         bin/cowrie start
       become: yes
       become_method: su
       become_user: cowrie
       async: 100

     - name: sleep 90sec
       wait_for: 
         timeout: 30

     - name: stop cowrie
       shell: |
         #sudo su - cowrie
         cd cowrie
         source cowrie-env/bin/activate
         bin/cowrie stop
       become: yes
       become_method: su
       become_user: cowrie
