- hosts: dockerd11
  tasks:
     - name: Get running dionaea
       shell: "ps -ef | grep -v grep | grep -w /opt/dionaea/bin/dionaea | awk '{print $2}'"
       register: running_processes

     - name: Kill running dionaea
       shell: "kill {{ item }}"
       with_items: "{{ running_processes.stdout_lines }}"

     - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
       with_items: "{{ running_processes.stdout_lines }}"
       ignore_errors: yes
       register: killed_processes

     - name: Force kill stuck dionaea
       shell: "kill -9 {{ item }}"
       with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
